### ISSUE TITLE
i3lock-color is out of date compared to i3lock

### ISSUE THREAD

**Issue by meskarune** [eBrnd/i3lock-color#6]
The i3lock package is ahead of i3lock-color by quite a bit. It would be amazing if i3lock-color could be updated with the latest i3lock. If you don't plan on maintaining this any longer I could perhaps try my hand, but I'm very new to C programming and may need some help knowing what exactly was changed to add the new features. This package is still widely used by many people and I would hate to see it get lost.

**Comment by Arcaena** [comment]
For anyone interested, I've rebased i3lock-color on current day i3lock [here](https://github.com/Arcaena/i3lock-color). I also fixed a couple bugs in the original i3lock-color.

**Comment by eBrnd** [comment]
Hey, thanks for posting here and reminding me this repo still exists, and sorry for not replying for so long!

I actually haven't looked at this repo in a while (I've been using 'standard' i3lock again). I'm actually surprised that people are still interested in this. Yes, it is out of date since it was more or less a proof-of-concept back then and I'm also not too happy with the way you have to specify the colors as lots of commandline arguments.

@meskarune if you want to take over this project that's cool! I'm just not quite sure what's the best way to do this on github - adding you as a contributor, or deleting my repo after you forked it, or just transferring it, or do you just want to send me pull requests..? If you have any question on the code itself feel free to ask. As far as I remember the diff to the original i3lock is quite small anyway.

However, from a quick look I think @Arcaena 's fork is the one that should be continued since it's not based on an outdated version of i3lock...

**Comment by Arcaena** [comment]
yeah, the original diff compared to i3lock at the time was pretty small but it had changed enough since then that it was easier to just fork off of i3lock and then patch in the stuff, otherwise I'dve directly forked this since that would've been proper.

That reminds me though, I actually did find a bug [here](https://github.com/eBrnd/i3lock-color/blob/master/unlock_indicator.c#L198-L201) that I fixed in my fork, should I do a pull request, or nah?

**Comment by eBrnd** [comment]
Sure, send me a pull request. At the moment I'm thinking about also changing the readme so it directs people to your repository if they actually want to use i3lock-color.

**Comment by Arcaena** [comment]
Alright, thanks! If you want to change the readme, that'd be awesome.

**Comment by eBrnd** [comment]
OK, merged your PR and added the note.

I'm closing that issue for now. Thanks again for bringing it up.

And sorry to @meskarune that I didn't notice the issue earlier. I just didn't notice the notification at the time - but maybe you two can communicate and make i3lock even cooler.

Also, there's two funny i3lock forks by @ravinrabbid who added SVG rendering and little clock hands in the circular indicator:

https://github.com/ravinrabbid/i3lock-svg
https://github.com/ravinrabbid/i3lock-clock
